### ISSUE TITLE
Theme Form

### ISSUE THREAD

**Issue by Bigmommba** [PGG-blackout-games/Blackoutgames-PGG#11]
We had gotten a new theme summation

From : Jackson allen shaver

Image url
https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.sportskeeda.com%2Fplayer%2Fstephen-wonderboy-thompson&psig=AOvVaw2_m4ckl__7SO6Phifsigc-&ust=1729880423845000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCKjI2vPQp4kDFQAAAAAdAAAAABAE

name : wonderboy

**Comment by WhoIsDada** [comment]
File Is Corrupt
