### ISSUE TITLE
User jackson allen shaver

### ISSUE THREAD

**Issue by Bigmommba** [PGG-blackout-games/Blackoutgames-PGG#21]
Name:  jacky poopoo bear
Picture Name  Wonderboy
Picture url:  https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.sportskeeda.com%2Fplayer%2Fstephen-wonderboy-thompson&psig=AOvVaw2_m4ckl__7SO6Phifsigc-&ust=1729880423845000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCKjI2vPQp4kDFQAAAAAdAAAAABAE
Received on Oct 24 at 2:21 PM from 163.120.64.212

**Comment by WhoIsDada** [comment]
non useable
